### ISSUE TITLE
运行Fid框架报错

### ISSUE THREAD

**Issue by gao18835258627** [RUC-NLPIR/FlashRAG#101]
修改配置：use_fid: True generator_model: "flan-t5-large"
运行命令：python run_exp.py --method_name 'naive' \
                  --split 'test' \
                  --dataset_name 'nq' \
                  --gpu_id '1'
报错1：input_prompts.append([q + " " + doc for doc in docs])这句话报错说不能append一个字典，然后我就改成了                input_prompts.append([q + " " + doc["contents"] for doc in docs])
报错2：Traceback (most recent call last):
  File "/home/xinyu/aaaa/examples/methods/run_exp.py", line 586, in <module>
    func(args)
  File "/home/xinyu/aaaa/examples/methods/run_exp.py", line 20, in naive
    result = pipeline.run(test_data)
  File "/home/xinyu/aaaa/flashrag/pipeline/pipeline.py", line 126, in run
    pred_answer_list = self.generator.generate(input_prompts)
  File "/home/xinyu/miniconda3/envs/Inter/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xinyu/aaaa/flashrag/generator/generator.py", line 131, in generate
    outputs = self.model.generate(**inputs, **generation_params)
TypeError: generate() got an unexpected keyword argument 'do_sample'
报错3：我试着将报错语句改为            outputs = self.model.generate(
                **inputs,
                # do_sample=True,
                # temperature=0.8,
                # top_p=0.9,
                max_length=256,
                # num_beams=1,
            )
又出现了新的错误Traceback (most recent call last):
  File "/home/xinyu/aaaa/examples/methods/run_exp.py", line 586, in <module>
    func(args)
  File "/home/xinyu/aaaa/examples/methods/run_exp.py", line 20, in naive
    result = pipeline.run(test_data)
  File "/home/xinyu/aaaa/flashrag/pipeline/pipeline.py", line 126, in run
    pred_answer_list = self.generator.generate(input_prompts)
  File "/home/xinyu/miniconda3/envs/Inter/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xinyu/aaaa/flashrag/generator/generator.py", line 136, in generate
    outputs = self.model.generate(
  File "/home/xinyu/aaaa/flashrag/generator/fid.py", line 41, in generate
    return super().generate(
  File "/home/xinyu/miniconda3/envs/Inter/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/xinyu/miniconda3/envs/Inter/lib/python3.9/site-packages/transformers/generation/utils.py", line 1987, in generate
    inputs_tensor, model_input_name, model_kwargs = self._prepare_model_inputs(
  File "/home/xinyu/miniconda3/envs/Inter/lib/python3.9/site-packages/transformers/generation/utils.py", line 487, in _prepare_model_inputs
    and self.encoder.main_input_name != self.main_input_name
  File "/home/xinyu/miniconda3/envs/Inter/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1931, in __getattr__
    raise AttributeError(
AttributeError: 'EncoderWrapper' object has no attribute 'main_input_name'

**Comment by ignorejjj** [comment]
是Fid的代码有一些版本问题，已经进行修复。目前在fid官方给出的checkpoint上进行测试没有问题。

**Comment by gao18835258627** [comment]
十分感谢您的耐心解答
