### ISSUE TITLE
local variable 'new_results' referenced before assignment (cache manager issue)

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#59]
Hello there,

I got this error
```
Traceback (most recent call last):
  File "/home/smalldog/FlashRAG/examples/methods/run_exp.py", line 473, in <module>
    func(args)
  File "/home/smalldog/FlashRAG/examples/methods/run_exp.py", line 20, in naive
    result = pipeline.run(test_data)
  File "/home/smalldog/FlashRAG/flashrag/pipeline/pipeline.py", line 83, in run
    retrieval_results = self.retriever.batch_search(input_query)
  File "/home/smalldog/FlashRAG/flashrag/retriever/retriever.py", line 70, in wrapper
    for query, doc_items, doc_scores in zip(query_list, new_results, new_scores):
UnboundLocalError: local variable 'new_results' referenced before assignment
```
when running command 
```
python run_exp.py --method_name 'naive' \
                  --split 'test' \
                  --dataset_name 'nq' \
                  --gpu_id '0,1,2,3'
```

In the config, I am using ```hf```, I think ```fschat``` has same error, haven't tested on ```vllm``` yet.
```
framework: hf # inference frame work of LLM, supporting: 'hf','vllm','fschat'
```

i think when ```query_list``` is already a list (normally), the code will not go inside the [if statement](https://github.com/RUC-NLPIR/FlashRAG/blob/main/flashrag/retriever/retriever.py#L62) ```if isinstance(query_list, str):``` to create the var ```new_results```.

**Comment by ignorejjj** [comment]
Sorry, this is a minor bug we introduced when modifying the cache process recently, and we have fixed it. See commit 82770111d0969100b654546bb18626c1a2fdf520.
