### ISSUE TITLE
LongLLMLingua always encounters a CUDA out of memory error

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#67]
Hello,

I tried to run the ```LongLLMLingua``` approach, but it always results in the ```CUDA out of memory``` error. I have tried running it on 8 * 80GB GPUs.

I set the ```refiner_model_path``` to ```"/workspace/models/Llama-2-7b-hf"``` in the ```llmlingua``` function in ```run_exp.py```.

The error message is below:
```
INFO 08-06 23:52:03 distributed_gpu_executor.py:56] # GPU blocks: 227076, # CPU blocks: 16384
[rank0]: Traceback (most recent call last):
[rank0]:   File "/workspace/FlashRAG/examples/methods/run_exp.py", line 562, in <module>
[rank0]:     func(args)
[rank0]:   File "/workspace/FlashRAG/examples/methods/run_exp.py", line 126, in llmlingua
[rank0]:     result = pipeline.run(test_data)
[rank0]:   File "/workspace/FlashRAG/flashrag/pipeline/pipeline.py", line 131, in run
[rank0]:     self.generator = get_generator(self.config)
[rank0]:   File "/workspace/FlashRAG/flashrag/utils/utils.py", line 33, in get_generator
[rank0]:     return getattr(importlib.import_module("flashrag.generator"), "VLLMGenerator")(config, **params)
[rank0]:   File "/workspace/FlashRAG/flashrag/generator/generator.py", line 194, in __init__
[rank0]:     self.model = LLM(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/entrypoints/llm.py", line 155, in __init__
[rank0]:     self.llm_engine = LLMEngine.from_engine_args(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 441, in from_engine_args
[rank0]:     engine = cls(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 265, in __init__
[rank0]:     self._initialize_kv_caches()
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/engine/llm_engine.py", line 377, in _initialize_kv_caches
[rank0]:     self.model_executor.initialize_cache(num_gpu_blocks, num_cpu_blocks)
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/distributed_gpu_executor.py", line 62, in initialize_cache
[rank0]:     self._run_workers("initialize_cache",
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/executor/multiproc_gpu_executor.py", line 178, in _run_workers
[rank0]:     driver_worker_output = driver_worker_method(*args, **kwargs)
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/worker/worker.py", line 219, in initialize_cache
[rank0]:     self._init_cache_engine()
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/worker/worker.py", line 224, in _init_cache_engine
[rank0]:     self.cache_engine = [
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/worker/worker.py", line 225, in <listcomp>
[rank0]:     CacheEngine(self.cache_config, self.model_config,
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 66, in __init__
[rank0]:     self.gpu_cache = self._allocate_kv_cache(
[rank0]:   File "/workspace/miniconda3/envs/flashrag-env-conda-torch/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 85, in _allocate_kv_cache
[rank0]:     torch.zeros(kv_cache_shape,
[rank0]: torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.73 GiB. GPU 
```
Can you take a look? Thank you!

**Comment by ignorejjj** [comment]
For vllm generator, you should set a suitable value for `gpu_cemory_utilization` in the config. If set too large, vllm will occupy more GPU memory. Here, the retriever and refiner may have already occupied some GPU memory, causing vllm to be unable to allocate the corresponding memory. Maybe you can change it to 0.5.

**Comment by codecodebear** [comment]
Thank you so much for the info! It works.
