### ISSUE TITLE
replug has a small bug

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#68]
Hello,

There is a tiny bug when running ```replug```.
the error is below:
```
Loading dataset shards: 100%|████████████████████████████████████████████████████| 28/28 [00:00<00:00, 93.61it/s]
Loading checkpoint shards: 100%|███████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.97it/s]
Traceback (most recent call last):
  File "/workspace/FlashRAG/examples/methods/run_exp.py", line 562, in <module>
    func(args)
  File "/workspace/FlashRAG/examples/methods/run_exp.py", line 286, in replug
    pipeline = REPLUGPipeline(config)
  File "/workspace/FlashRAG/flashrag/pipeline/branching_pipeline.py", line 20, in __init__
    self.generator = get_generator(config, model=model)
  File "/workspace/FlashRAG/flashrag/utils/utils.py", line 33, in get_generator
    return getattr(importlib.import_module("flashrag.generator"), "VLLMGenerator")(config, **params)
TypeError: VLLMGenerator.__init__() got an unexpected keyword argument 'model'
```
Can you take a look? Thank you so much.

**Comment by ignorejjj** [comment]
This is not a bug. Since replug need a custom logit execution function, the vllm framework is currently not supported. Change framework to hf or fschat.

**Comment by codecodebear** [comment]
Hi, sorry I didn't think carefully on it.
Switching to hf or fschat works.
