### ISSUE TITLE
recomp has an issue

### ISSUE THREAD

**Issue by codecodebear** [RUC-NLPIR/FlashRAG#75]
Hi
I encountered a small issue when running ```recomp```:
```
Traceback (most recent call last):
  File "/workspace/FlashRAG/examples/methods/run_exp.py", line 564, in <module>
    func(args)
  File "/workspace/FlashRAG/examples/methods/run_exp.py", line 171, in recomp
    pipeline = SequentialPipeline(config)
  File "/workspace/FlashRAG/flashrag/pipeline/pipeline.py", line 110, in __init__
    self.refiner = get_refiner(config, self.retriever, self.generator)
  File "/workspace/FlashRAG/flashrag/utils/utils.py", line 104, in get_refiner
    if model_config.model_type == "t5":
UnboundLocalError: local variable 'model_config' referenced before assignment
```
I haven't looked deeply into it, ```recomp``` worked a few days ago.
Can you take a look if you have time? Thank you!

**Comment by ignorejjj** [comment]
I'm not quite sure about the reason for this issue, maybe you didn't fill in the refiner_path correctly? However, I have optimized the logic of this part and it should now run normally.
