### ISSUE TITLE
环境配置问题：vllm

### ISSUE THREAD

**Issue by Beyond0831** [RUC-NLPIR/FlashRAG#77]
Collecting vllm>=0.4.1 (from flashrag==0.0.1)
我在跟着新手教程配置环境的时候，出现了以下问题（vllm下载无法成功），并且即使我尝试使用虚拟环境安装也无法成功，所以我想请问以下问题是否有办法解决，目前我不太清楚问题原因， 目前我是在windows下跑的，终端用的是cmd
![image](https://github.com/user-attachments/assets/093dc811-f7f9-4bef-982f-e7922a3b88b8)

  
  Downloading vllm-0.5.4.tar.gz (958 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 958.6/958.6 kB 5.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "D:\AgentScope\FlashRAG\flashrag\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\AgentScope\FlashRAG\flashrag\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AgentScope\FlashRAG\flashrag\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11142\AppData\Local\Temp\pip-build-env-o4hnprmq\overlay\Lib\site-packages\setuptools\build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\11142\AppData\Local\Temp\pip-build-env-o4hnprmq\overlay\Lib\site-packages\setuptools\build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "C:\Users\11142\AppData\Local\Temp\pip-build-env-o4hnprmq\overlay\Lib\site-packages\setuptools\build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 12, in <module>
        File "C:\Users\11142\AppData\Local\Temp\pip-build-env-o4hnprmq\overlay\Lib\site-packages\torch\__init__.py", line 148, in <module>
          raise err
      OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\11142\AppData\Local\Temp\pip-build-env-o4hnprmq\overlay\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by ignorejjj** [comment]
vllm只支持linux系统，windows系统用不了。可以把`requirements.txt`里面的`vllm`删掉，装剩下的包。

**Comment by Beyond0831** [comment]
> vllm只支持linux系统，windows系统用不了。可以把`requirements.txt`里面的`vllm`删掉，装剩下的包。

![image](https://github.com/user-attachments/assets/81f9bd72-9d7f-4cfb-9744-98eb53eab7d2)
 nmslib在尝试下载时我遇到好像缺少C++工具的问题，导致也无法下载成功，这个环境包也是必须的吗，还是说也可以删除？

**Comment by ignorejjj** [comment]
可以把里面的`pyserini`库删掉，但会导致无法使用bm25检索功能。

**Comment by Beyond0831** [comment]
> 可以把里面的`pyserini`库删掉，但会导致无法使用bm25检索功能。

感谢回答！ 还有一个和当前问题不相关的问题我想询问，教程中提到下载模型，是指需要本地部署吗？ 我目前想尝试使用agentscope内嵌flashrag的功能，实现远程的rag model调用，请问这可以实现吗

**Comment by ignorejjj** [comment]
模型可以在本地或者服务器上部署。理论上是能跟agentscope结合使用的。
