### ISSUE TITLE
IndexError: Invalid key: 16315106 is out of bounds for size 15000

### ISSUE THREAD

**Issue by hahaha1121871443** [RUC-NLPIR/FlashRAG#95]
您好！我想问一下，当我直接使用您提供的wiki18_100w_e5.index作为e5的索引时发生报错：对nq中的test.jsonl运行simple_pipeline.py时发生报错：IndexError: Invalid key: 16315106 is out of bounds for size 15000，这是什么原因呢？

**Comment by hahaha1121871443** [comment]
报错信息是：
Traceback (most recent call last):
  File "/home/lh1121871443/FlashRAG-main/examples/quick_start/simple_pipeline.py", line 47, in <module>
    output_dataset = pipeline.run(test_data, do_eval=True)
  File "/home/lh1121871443/FlashRAG-main/flashrag/pipeline/pipeline.py", line 87, in run
    retrieval_results = self.retriever.batch_search(input_query)
  File "/home/lh1121871443/FlashRAG-main/flashrag/retriever/retriever.py", line 66, in wrapper
    results, scores = func(self, query_list, num, True)
  File "/home/lh1121871443/FlashRAG-main/flashrag/retriever/retriever.py", line 97, in wrapper
    results, scores = func(self, query_list, num, True)
  File "/home/lh1121871443/FlashRAG-main/flashrag/retriever/retriever.py", line 171, in batch_search
    return self._batch_search(*args, **kwargs)
  File "/home/lh1121871443/FlashRAG-main/flashrag/retriever/retriever.py", line 354, in _batch_search
    batch_results = load_docs(self.corpus, flat_idxs)
  File "/home/lh1121871443/FlashRAG-main/flashrag/retriever/utils.py", line 96, in load_docs
    results = [corpus[int(idx)] for idx in doc_idxs]
  File "/home/lh1121871443/FlashRAG-main/flashrag/retriever/utils.py", line 96, in <listcomp>
    results = [corpus[int(idx)] for idx in doc_idxs]
  File "/home/lh1121871443/anaconda3/envs/frag/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2762, in __getitem__
    return self._getitem(key)
  File "/home/lh1121871443/anaconda3/envs/frag/lib/python3.9/site-packages/datasets/arrow_dataset.py", line 2746, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices)
  File "/home/lh1121871443/anaconda3/envs/frag/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 593, in query_table
    _check_valid_index_key(key, size)
  File "/home/lh1121871443/anaconda3/envs/frag/lib/python3.9/site-packages/datasets/formatting/formatting.py", line 533, in _check_valid_index_key
    raise IndexError(f"Invalid key: {key} is out of bounds for size {size}")
IndexError: Invalid key: 16315106 is out of bounds for size 15000

**Comment by hahaha1121871443** [comment]
哦，不好意思，我明白了。这是因为我将wiki18_100w_e5.index设置为索引路径，但是我的语料库仍为generalknowledge，导致了超出了size的范围。我将关闭这个问题。
